server:
  port: 8440
spring:
  application:
    name: trade-service
  datasource:
    url: jdbc:mysql://localhost/learning?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis:
  mapper-locations: classpath:mapper/*.xml
alipay:
  protocol: https
  gatewayHost: openapi-sandbox.dl.alipaydev.com
  appId: 9021000149682820
  signType: RSA2
  merchantPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCL2BtCJD5vEjTRQdAvyXv6IjEH82hGWmNKMItXrcaIfP1BqIZfTj4o9YCgL+/8VPRnyzO00Vue4Aj/Nz3aXne6Phs09PFtXY6iviAbhTSqofMpRF6Fs0sdGbCvy5+q3yOYLsMnTFINlfKbEx2VT6mZBZuLH/cNyjIrPzQJ2Bqny3QdJ7EJ79LqWV2KiFOHffbRsi61c3QMNXNAcOiOc4MUSGpCcQkdHtaTygNPJ9X5U7DZD9DTaE3mhUZWSYtGeFTZLDKuFko3L+opKp9FcuC8aqV2ud6nECK5feBx5jmk3neT8iSd7v95+fJ67pabFXbXm6HnphFOI9L6dnqDQ1VhAgMBAAECggEAa2DKvWS7E+o06CDSzH63VX9/io1aGfs5ljPkKrTiZtciV5Iha3jWvfiUhWuJqIVLDY+36jV/VmTMQ7uVIOG8qSMbHPSflMxrw4adfMQxhnvIDH3U3nCnUnbxdmqx9TBVUntFmh0+O/RRTsXEx2td3IOzxYYL22jQUOi8+noXLZMi87hsPqxFcEGR3f0OImU73/pA/2mwOeMlF8ZzruEfJh6I9uMYtetDmdoN8DRskayLP76sVlXkJ+tulfZGJ9axsx6SLFpoSgycqqDlpXAKxRgLaLuPwPUOsjnHzOvkqMUYXaUeIWo0Z68KzCovxA7+tLXsyJz9+KDnxJ7Tz1pZyQKBgQDejPPDtOynCzszF1BAAjugd0B7ykkp8keItf45k1kUwmHqESiH9s2NXp8F2SYPOmuNCKu9L1LYl4kp92awkyHqEP1GE7XVdg4VxAUcl84AKtezuuLJc2DUd/iYzpoAdYR6A+gciSWFXwsn0OIB66DwQIqYDyh7tz/LTpSzjVNDLwKBgQCg3N7mLxweXgoPeDhe5VcFSX4oXUIesvoe3Qv0X8vDAYYNJxPx+CK9fHEfsl7JmBXjy3TqQZf+iFxb2i+uYUQTK6XJO1q5fakdtMD8OIwuxilm4POj3aKW3/SEaqhybFatkTEIDuJVieiaZovx++w0R7PSjgjuVUgAmkG4Zm0MbwKBgQC4vsHNAPBDaytlqkDQIgpllxlMqgw6agnAD3RPT2ZvuT2XFU9ULylL5fSU4kKZ+aE2nrASiKp5arJOyDXS9xD8QcY+2jXkUfA3WVX0+n/j26zcYpPJL6J+Pml8UGW/Y87pizywE5m2McQM9XXoqjYbuzhSKqMssF6g40bGFte7uQKBgCLGnQl2NcX63oHpo4YgXmeuM6/WOW0ZlCkH8IWsEAjgU3KUeCNfWWNNe8c2cHd0gYb1fRkHhSxpnk3dJWG1dVoPnY+bXUmseNsLMI1WTDfwbxLmnsVWLMghMmNOC4xxD2wGb2smjJehcL+wW6C8rZu/xIhIXHXpyd8Xeg27VufRAoGAR8vEbAT+a0CSsO5Sw1IzdxmVWwsfGjyTOTCj+Rr2IAx8NKiB9fZ6RocNvwRw9s1ezEhMvUomJJNfBNKVt5z+Cfp+T2KmR7/Mb3OHuHY4vo38YThcrmZSkgdXNrRTT9Gagp0Jxa7P61fa0gh1YSaLoaruhzTCzaFBuxLXgHcPwMI=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiL2KG2X1bmtmY9zHmq5MkAafopKQE3BI69JanNhvM4RnCOMlMh75aoKTNSS/ftc536pw2kgbvnnPQIgpP+z63a1nv3+U8fCNPdQjGARuDjhc89pd6r5z1gLrXZ4dUhBYpoDIef60I4FaW5cUnawlsmZkVperudBHpyhhX3OFTHIeUxNI+9Gpj9spBFWWszuQ9YL5fKszGrO9tHCIYsiAsuIN4u+d5tNphzC4yDHX19OyyLcSdrguO3wv5dwAdRP/+Hwd+2wfWasgDePvFu2KgaUBSilJRz6takCLRg1eeiBtiKal0CX3NpS7oRXstaWAXF5woQVlNfLn28UGe8+gIwIDAQAB
gateway:
  protocol: http
  host: 127.0.0.1:8080