server:
  port: 8080

spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          # 【建议】使用标准的 http:// 协议头，更清晰
          jwk-set-uri: http://localhost:8846/oauth/key
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          # 让网关能根据服务名自动创建路由，这是一个好习惯
          enabled: true

      # ================== 【核心修正：CORS 配置】 ==================
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          # 【修正1】将路径匹配模式从 '[/]' 改为 '[/**]'，以匹配所有路径
          '[/**]':
            # 【修正2】将源地址从 3000 改为 3001，与你的前端保持一致
            allowedOrigins: "http://localhost:3001"
            # 【修正3】允许所有请求方法，更通用
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            # 【修正4】允许所有请求头，避免未来因自定义请求头导致的问题
            allowedHeaders: "*"
            # 允许携带 cookie 和认证信息
            allowCredentials: true
            # 预检请求的缓存时间
            maxAge: 360000

      # ================== 【路由配置】 ==================
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/oauth/** # 路径末尾加上 ** 更精确
          filters:
            - StripPrefix=1

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /api/roles/**
          filters:
            - StripPrefix=1

        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/courses/**, /api/categories/**, /api/chapters/**, /api/questions/**, /api/answers/**, /api/notes/**, /api/evaluations/**
          filters:
            - StripPrefix=1

        - id: trade-service
          uri: lb://trade-service
          predicates:
            - Path=/api/orders/**, /api/payments/**
          filters:
            - StripPrefix=1

        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/videos/**, /api/cover-pictures/**, /api/profile-pictures/**
          filters:
            - StripPrefix=1

        # 这个路由的 StripPrefix 过滤器可能需要保留，取决于你的 MinIO 存储桶结构
        - id: dfs
          uri: http://localhost:9000
          predicates:
            - Path=/dfs/**
          filters:
            # 当请求 /dfs/videos/xxx 时，转发到 MinIO 的是 /videos/xxx
            - StripPrefix=1

# 【可选但建议】移除这个，因为它不是 spring cloud gateway 的标准配置项，可能会引起未知问题
# add-to-simple-url-handler-mapping: true